# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07bb5f091179452f8d724194f71e1eade360af3b9933aca248c1fdae0c2102aaf2303ea6da0fcd69f78eae0659171e780db561bd92c914b0d020eb0b991b0b7

test:
  secret_key_base: 0294839f56fbc6166721e2eff56762426dc58fcbae3955ae3e9b4bc2e4470b85ef0cbc13c3ecdacdc80063db608e63602b9a630772c7f38e51d26fe4d1e0ce01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
