# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb45ed844935287e9ede8a9dded914115469d8cea293c47509cc8d7f61146f98d97f974a04ac608c80e801ee9acc72ca85dc850a5157040f68d7a56c1de354f

test:
  secret_key_base: 054b6e9f6e47729edc2b62f9f38848a454aca498b9f5f38c76907b3d2ae9c436549d51f6c0c26ee1cc41853e869ed4a644c651840b4001c32ea110cc33368118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
